### ISSUE TITLE
getFinancialYear & getFinancialPeriod format options

### ISSUE THREAD

**Issue by regatta-ajd** [regattadev/dates#1]
@duncan3dc 
As a reminder :
Could the `getFinancialYear()` & `getFinancialPeriod()` methods be updated to accept a format. Formats would be restricted to year formats for `getFinancialYear()` and month formats for `getFinancialPeriod()`. 
We may also want another method for the `1ym` format that is sometimes used?

**Comment by duncan3dc** [comment]
@regatta-ajd Yeh that thought just occurred to me as well. And then I thought we might want to use the `string()` method, or the `numeric()` method.

I'm wondering now if a `Period` object would be better that extends the Date class, and restricts the formats allowed in `format()`, `string()`, etc. Giving maximum flexibility and avoiding accidental misuse.

This could be done in addition to making `getFinancialYear()` accept a format

**Comment by duncan3dc** [comment]
`formatPeriod()` is available in 0.4.0
`getFinancialYear()` and `getFinancialPeriod()` have been left as they were
