### ISSUE TITLE
format() function strips leading zeroes

### ISSUE THREAD

**Issue by regatta-anp** [regattadev/dates#15]
format() function has inconsistent behaviour to the php function ``string date ( string $format [, int $timestamp = time() ] )``

Leading zeroes are stripped from formatting when expected. For example, following code should return "01". Instead it returns 1.

Date::now()->format("m"); // Note called in month of January.

Looks like issue might be with following code block

https://github.com/regattadev/dates/blob/master/src/Traits/Formatting.php#L56

**Comment by regatta-ajl** [comment]
I think you should be able to use the string function to retrieve the php standard result:

```php
Date::now()->string("m");
```

**Comment by regatta-anp** [comment]
@regatta-ajl Ah, thanks Andy. Will give that a try

**Comment by duncan3dc** [comment]
`format()` uses type juggling, so if the result looks like a number, you get an integer.

Most of the time you should use `string()` and 'numeric()`

Is this missing from the documentation?

**Comment by regatta-anp** [comment]
Sorry, my mistake. Will use string() instead. Documentation is correct.

Closed this issue
