### ISSUE TITLE
Access to Season::$type

### ISSUE THREAD

**Issue by regatta-ajd** [regattadev/dates#3]
It would be useful in some cases to have access to the type of a season. Could we add a `getType()` method or `isSpringSummer()` / `isAutumnWinter()` ?

**Comment by duncan3dc** [comment]
Yep, all of those make sense, I'll get them added

**Comment by duncan3dc** [comment]
Available in 0.6.2

**Comment by regatta-ajd** [comment]
@duncan3dc 
Thanks :+1:
