### ISSUE TITLE
Month::addYears() & Month::subYears()

### ISSUE THREAD

**Issue by regatta-ajd** [regattadev/dates#4]
Would it be possible to add the `addYears()` and `subYears()` methods to the `Month` class
This would avoid having to write code like this :
```PHP
$month->getStart()->subYears(1)->getMonth();
```

**Comment by duncan3dc** [comment]
Available in 0.7.0 (as well as a bunch of others, eg `Year::addYears()`, `Season::addYears()`, etc)
```php
$month = $month->subYears(1);
```
